name: Vigilante de Vinted

on:
  schedule:
    - cron: '13 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependencias del sistema (Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependencias de Python
        run: |
          pip install selenium beautifulsoup4 requests

      - name: Ejecutar script
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          cd Script
          python VintedBot.py
