name: Vigilante de Vinted

on:
  schedule:
    - cron: '13 * * * *' # Se ejecuta cada hora en el minuto 13
  workflow_dispatch:      # Permite ejecutarlo manualmente desde la web

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Permite al script hacer "git push" del historial
    steps:
      - name: Descargar código
        uses: actions/checkout@v4 # Actualizado a la versión más reciente

      - name: Instalar Python
        uses: actions/setup-python@v5 # Actualizado a la versión más reciente
        with:
          python-version: '3.13'

      - name: Instalar dependencias del sistema (Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependencias de Python
        run: |
          pip install selenium beautifulsoup4 requests

      - name: Ejecutar script
        env:
          # Traemos los tokens de forma segura desde los Secrets de GitHub
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          cd Script
          python VintedBot.py